# Generated by Django 5.1.4 on 2026-04-27 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='EUR', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='clients.businessclient')),
            ],
            options={
                'ordering': ('category', 'name'),
                'unique_together': {('business_client', 'name')},
            },
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=160)),
                ('role_title', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('color', models.CharField(default='#3b82f6', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='clients.businessclient')),
            ],
            options={
                'ordering': ('full_name',),
            },
        ),
        migrations.CreateModel(
            name='BlockedTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('source', models.CharField(default='manual', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_times', to='clients.businessclient')),
                ('staff_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocked_times', to='staff_services.staffmember')),
            ],
            options={
                'ordering': ('start_at',),
            },
        ),
        migrations.CreateModel(
            name='StaffService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_services', to='staff_services.service')),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_services', to='staff_services.staffmember')),
            ],
        ),
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Ponedeljak'), (1, 'Utorak'), (2, 'Sreda'), (3, 'Cetvrtak'), (4, 'Petak'), (5, 'Subota'), (6, 'Nedelja')])),
                ('start_time', models.TimeField(default='09:00')),
                ('end_time', models.TimeField(default='16:00')),
                ('is_closed', models.BooleanField(default=False)),
                ('business_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='clients.businessclient')),
                ('staff_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='staff_services.staffmember')),
            ],
            options={
                'ordering': ('weekday', 'start_time'),
            },
        ),
        migrations.AddIndex(
            model_name='staffmember',
            index=models.Index(fields=['business_client', 'is_active'], name='staff_servi_busines_21175b_idx'),
        ),
        migrations.AddIndex(
            model_name='blockedtime',
            index=models.Index(fields=['business_client', 'start_at', 'end_at'], name='staff_servi_busines_ea68bc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='staffservice',
            unique_together={('staff_member', 'service')},
        ),
        migrations.AlterUniqueTogether(
            name='workinghours',
            unique_together={('business_client', 'staff_member', 'weekday')},
        ),
    ]
