# Generated by Django 5.1.4 on 2026-05-06 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_business_client_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'God Mode admin'), ('client', 'Administrator / company'), ('employee', 'Employee')], default='client', max_length=20),
        ),
    ]
