# Generated by Django 5.1.4 on 2026-04-27 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0002_appointment_metadata'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('phone', 'Telefon'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('viber', 'Viber'), ('email', 'Email'), ('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('web', 'Web')], max_length=30)),
                ('status', models.CharField(choices=[('open', 'Otvoren'), ('waiting', 'Ceka odgovor'), ('closed', 'Zatvoren'), ('handoff', 'Prebaceno supportu')], default='open', max_length=30)),
                ('external_thread_id', models.CharField(blank=True, max_length=180)),
                ('language', models.CharField(default='en', max_length=10)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='clients.businessclient')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='appointments.customer')),
            ],
            options={
                'ordering': ('-last_message_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='CallSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='manual', max_length=80)),
                ('external_call_id', models.CharField(blank=True, max_length=180)),
                ('status', models.CharField(choices=[('ringing', 'Zvoni'), ('active', 'Aktivan'), ('completed', 'Zavrsen'), ('missed', 'Propusten'), ('failed', 'Greska')], default='ringing', max_length=30)),
                ('from_number', models.CharField(blank=True, max_length=60)),
                ('to_number', models.CharField(blank=True, max_length=60)),
                ('transcript', models.TextField(blank=True)),
                ('recording_url', models.URLField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_sessions', to='clients.businessclient')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_sessions', to='appointments.customer')),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_sessions', to='communications.conversation')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('inbound', 'Dolazna'), ('outbound', 'Odlazna'), ('internal', 'Interna')], max_length=30)),
                ('message_type', models.CharField(choices=[('text', 'Tekst'), ('voice', 'Glas'), ('email', 'Email'), ('system', 'Sistem')], default='text', max_length=30)),
                ('sender_label', models.CharField(blank=True, max_length=120)),
                ('body', models.TextField(blank=True)),
                ('provider_message_id', models.CharField(blank=True, max_length=180)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='communications.conversation')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['business_client', 'channel', 'status'], name='communicati_busines_73dcb4_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['external_thread_id'], name='communicati_externa_a19726_idx'),
        ),
        migrations.AddIndex(
            model_name='callsession',
            index=models.Index(fields=['business_client', 'status', 'created_at'], name='communicati_busines_27ea76_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='communicati_convers_b5d10e_idx'),
        ),
    ]
