# Generated by Django 5.1.4 on 2026-05-31 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_alter_conversation_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callsession',
            name='status',
            field=models.CharField(choices=[('ringing', 'Zvoni'), ('active', 'Aktivan'), ('transferred', 'Prenet na vlasnika'), ('completed', 'Zavrsen'), ('missed', 'Propusten'), ('failed', 'Greska')], default='ringing', max_length=30),
        ),
    ]
