# Generated by Django 5.1.4 on 2026-04-27 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0002_appointment_metadata'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('appointment_created', 'Termin zakazan'), ('appointment_changed', 'Termin promenjen'), ('appointment_cancelled', 'Termin otkazan'), ('reminder_before', 'Podsetnik pre termina'), ('support_needed', 'Potreban support'), ('daily_report', 'Dnevni izvestaj')], max_length=60)),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('viber', 'Viber'), ('email', 'Email'), ('push', 'Push'), ('dashboard', 'Dashboard')], max_length=30)),
                ('offset_minutes', models.IntegerField(default=0)),
                ('language', models.CharField(default='en', max_length=10)),
                ('template', models.TextField(blank=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_rules', to='clients.businessclient')),
            ],
            options={
                'ordering': ('event', 'channel', 'offset_minutes'),
            },
        ),
        migrations.CreateModel(
            name='NotificationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Ceka'), ('processing', 'Obradjuje se'), ('sent', 'Poslato'), ('failed', 'Greska'), ('cancelled', 'Otkazano')], default='pending', max_length=30)),
                ('scheduled_for', models.DateTimeField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_jobs', to='appointments.appointment')),
                ('business_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_jobs', to='clients.businessclient')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_jobs', to='appointments.customer')),
            ],
            options={
                'ordering': ('scheduled_for',),
                'indexes': [models.Index(fields=['business_client', 'status', 'scheduled_for'], name='notificatio_busines_998bcd_idx')],
            },
        ),
    ]
