# Generated by Django 5.1.4 on 2026-04-26 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('basic', 'Basic'), ('pro', 'Pro'), ('business', 'Business'), ('god_mode', 'GOD MODE')], max_length=40, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('monthly_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='EUR', max_length=10)),
                ('trial_days', models.PositiveIntegerField(default=14)),
                ('is_contact_only', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('features', models.JSONField(blank=True, default=list)),
                ('active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('sort_order', 'monthly_price'),
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('past_due', 'Past due'), ('cancelled', 'Cancelled')], default='trial', max_length=30)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('external_customer_id', models.CharField(blank=True, max_length=160)),
                ('external_subscription_id', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='clients.businessclient')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.plan')),
            ],
        ),
    ]
