# Generated by Django 5.1.4 on 2026-04-28 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='code',
            field=models.CharField(choices=[('basic', 'Basic'), ('pro', 'Pro'), ('business', 'Business'), ('business_plus', 'Business+'), ('business_pro_plus', 'BusinessPro+'), ('god_mode', 'GOD MODE')], max_length=40, unique=True),
        ),
    ]
