# Generated by Django 5.1.4 on 2026-04-29 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_plan_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='allow_client_api_override',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='allow_instagram_dm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='allow_more_languages_by_agreement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='allow_phone_calls',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='allow_sms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='allow_telegram',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='allow_tiktok_dm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='allow_viber',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='allow_whatsapp',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='includes_elevenlabs_voice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_staff_members',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
