# Generated by Django 5.1.4 on 2026-05-01 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_plan_allow_client_api_override_and_more'),
        ('clients', '0004_alter_businessclient_interface_language_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('manual', 'Manual'), ('stripe', 'Stripe')], default='manual', max_length=40)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('provider_pending', 'Provider pending'), ('manual_contact', 'Manual contact'), ('paid', 'Paid'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='draft', max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('company', models.CharField(blank=True, max_length=160)),
                ('full_name', models.CharField(blank=True, max_length=160)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('trial_days', models.PositiveIntegerField(default=14)),
                ('checkout_url', models.URLField(blank=True)),
                ('external_checkout_id', models.CharField(blank=True, max_length=180)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkout_sessions', to='clients.businessclient')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkout_sessions', to='billing.plan')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
