# Generated by Django 5.1.4 on 2026-05-01 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_checkoutsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutsession',
            name='provider',
            field=models.CharField(choices=[('manual', 'Manual'), ('paypal', 'PayPal'), ('stripe', 'Stripe')], default='manual', max_length=40),
        ),
    ]
