# Generated by Django 5.1.4 on 2026-05-07 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_pendingcheckoutregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='lemonsqueezy', max_length=40)),
                ('event_name', models.CharField(blank=True, max_length=120)),
                ('external_event_id', models.CharField(blank=True, max_length=180)),
                ('external_object_id', models.CharField(blank=True, max_length=180)),
                ('status', models.CharField(choices=[('received', 'Received'), ('verified', 'Verified'), ('processed', 'Processed'), ('ignored', 'Ignored'), ('failed', 'Failed')], default='received', max_length=30)),
                ('signature_valid', models.BooleanField(default=False)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('raw_body', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checkout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='billing.checkoutsession')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['provider', 'event_name', 'status'], name='billing_pay_provide_dd9a99_idx'), models.Index(fields=['external_object_id'], name='billing_pay_externa_1424cb_idx'), models.Index(fields=['created_at'], name='billing_pay_created_f5c977_idx')],
            },
        ),
    ]
