# Generated by Django 5.1.4 on 2026-04-27 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIToolRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('planned', 'Planirano'), ('success', 'Uspesno'), ('failed', 'Greska'), ('skipped', 'Preskoceno')], default='planned', max_length=30)),
                ('input_payload', models.JSONField(blank=True, default=dict)),
                ('output_payload', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AIIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent', models.CharField(choices=[('book_appointment', 'Zakazivanje termina'), ('reschedule_appointment', 'Pomeranje termina'), ('cancel_appointment', 'Otkazivanje termina'), ('check_availability', 'Provera slobodnih termina'), ('business_info', 'Informacije o firmi'), ('support_handoff', 'Prebacivanje supportu'), ('unknown', 'Nepoznato')], default='unknown', max_length=60)),
                ('confidence', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('input_text', models.TextField()),
                ('language', models.CharField(default='en', max_length=10)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_intents', to='clients.businessclient')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
