# Generated by Django 5.1.4 on 2026-04-27 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_agent', '0001_initial'),
        ('appointments', '0002_appointment_metadata'),
        ('clients', '0001_initial'),
        ('communications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiintent',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_intents', to='communications.conversation'),
        ),
        migrations.AddField(
            model_name='aiintent',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_intents', to='appointments.customer'),
        ),
        migrations.AddField(
            model_name='aitoolrun',
            name='business_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_tool_runs', to='clients.businessclient'),
        ),
        migrations.AddField(
            model_name='aitoolrun',
            name='intent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tool_runs', to='ai_agent.aiintent'),
        ),
        migrations.AddIndex(
            model_name='aiintent',
            index=models.Index(fields=['business_client', 'intent', 'created_at'], name='ai_agent_ai_busines_d9a2f7_idx'),
        ),
        migrations.AddIndex(
            model_name='aitoolrun',
            index=models.Index(fields=['business_client', 'tool_name', 'status'], name='ai_agent_ai_busines_40a452_idx'),
        ),
    ]
