# Generated by Django 5.1.4 on 2026-05-13 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agent', '0002_initial'),
        ('appointments', '0003_appointment_service_appointment_staff_member_and_more'),
        ('clients', '0007_clientapisettings_master_prompt'),
        ('staff_services', '0002_staffmember_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True)),
                ('routine_notes', models.TextField(blank=True)),
                ('preferences', models.JSONField(blank=True, default=dict)),
                ('appointment_count', models.PositiveIntegerField(default=0)),
                ('cancellation_count', models.PositiveIntegerField(default=0)),
                ('reschedule_count', models.PositiveIntegerField(default=0)),
                ('no_show_risk', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=20)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_appointment_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(default='kaleya_ai', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_memories', to='clients.businessclient')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_memory', to='appointments.customer')),
                ('last_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_memories', to='staff_services.service')),
                ('preferred_staff_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_memories', to='staff_services.staffmember')),
            ],
            options={
                'ordering': ('customer__first_name', 'customer__last_name'),
                'indexes': [models.Index(fields=['business_client', 'no_show_risk'], name='ai_agent_cu_busines_606d2a_idx'), models.Index(fields=['business_client', 'updated_at'], name='ai_agent_cu_busines_eee894_idx')],
            },
        ),
    ]
