# Generated by Django 5.1.4 on 2026-05-13 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agent', '0003_customer_memory'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermemory',
            name='identifiers',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
