# Generated by Django 5.1.4 on 2026-04-26 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(blank=True, max_length=80)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('preferred_channel', models.CharField(default='phone', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='clients.businessclient')),
            ],
            options={
                'ordering': ('first_name', 'last_name'),
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=160)),
                ('status', models.CharField(choices=[('confirmed', 'Zakazano'), ('moved', 'Pomereno'), ('cancelled', 'Otkazano'), ('pending', 'Za proveru'), ('blocked', 'Blokirano')], default='confirmed', max_length=30)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('channel', models.CharField(choices=[('phone', 'Phone'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('viber', 'Viber'), ('telegram', 'Telegram'), ('web', 'Web')], default='phone', max_length=30)),
                ('source', models.CharField(default='manual', max_length=80)),
                ('notes', models.TextField(blank=True)),
                ('cancelled_reason', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='clients.businessclient')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='appointments.customer')),
            ],
            options={
                'ordering': ('date', 'start_time'),
                'indexes': [models.Index(fields=['business_client', 'date', 'start_time'], name='appointment_busines_37c103_idx'), models.Index(fields=['business_client', 'status'], name='appointment_busines_a4b8b5_idx')],
            },
        ),
    ]
