# Generated by Django 5.1.4 on 2026-04-27 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
