# Generated by Django 5.1.4 on 2026-04-27 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_metadata'),
        ('staff_services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='staff_services.service'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='staff_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='staff_services.staffmember'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='channel',
            field=models.CharField(choices=[('phone', 'Phone'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('viber', 'Viber'), ('telegram', 'Telegram'), ('email', 'Email'), ('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('web', 'Web')], default='phone', max_length=30),
        ),
    ]
