# Generated by Django 5.1.4 on 2026-05-31 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_appointment_is_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('moved', 'Rescheduled'), ('cancelled', 'Cancelled'), ('pending', 'Pending'), ('blocked', 'Blocked')], default='confirmed', max_length=30),
        ),
    ]
