# Generated by Django 5.1.4 on 2026-04-26 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('viber', 'Viber'), ('telegram', 'Telegram'), ('sms', 'SMS'), ('phone', 'Phone Call')], max_length=30)),
                ('enabled', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('connected', 'Connected'), ('paused', 'Paused'), ('error', 'Error')], default='draft', max_length=30)),
                ('public_number', models.CharField(blank=True, max_length=80)),
                ('webhook_url', models.URLField(blank=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='clients.businessclient')),
            ],
            options={
                'ordering': ('provider',),
                'unique_together': {('business_client', 'provider')},
            },
        ),
    ]
