# Generated by Django 5.1.4 on 2026-04-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationconnection',
            name='provider',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('viber', 'Viber'), ('telegram', 'Telegram'), ('sms', 'SMS'), ('phone', 'Phone Call'), ('email', 'Email'), ('google_calendar', 'Google Calendar'), ('instagram', 'Instagram'), ('tiktok', 'TikTok')], max_length=30),
        ),
    ]
