# Generated by Django 5.1.4 on 2026-04-26 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalAISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_provider', models.CharField(default='openai', max_length=80)),
                ('ai_model', models.CharField(default='gpt-4o-mini', max_length=120)),
                ('ai_api_key', models.CharField(blank=True, max_length=500)),
                ('voice_provider', models.CharField(default='elevenlabs', max_length=80)),
                ('voice_model', models.CharField(blank=True, max_length=120)),
                ('voice_api_key', models.CharField(blank=True, max_length=500)),
                ('enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Global AI settings',
            },
        ),
        migrations.CreateModel(
            name='AlarmSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('urgent_enabled', models.BooleanField(default=True)),
                ('announcement_enabled', models.BooleanField(default=True)),
                ('notification_sound', models.CharField(default='soft-bell', max_length=160)),
                ('urgent_sound', models.CharField(default='urgent-pulse', max_length=160)),
                ('announcement_sound', models.CharField(default='airport-chime', max_length=160)),
                ('notification_volume', models.PositiveIntegerField(default=55)),
                ('urgent_volume', models.PositiveIntegerField(default=85)),
                ('announcement_volume', models.PositiveIntegerField(default=70)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alarm_settings', to='clients.businessclient')),
            ],
        ),
        migrations.CreateModel(
            name='KaleyaCommandLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=120)),
                ('input_text', models.TextField(blank=True)),
                ('output_text', models.TextField(blank=True)),
                ('language', models.CharField(default='en', max_length=10)),
                ('channel', models.CharField(default='web', max_length=30)),
                ('success', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kaleya_command_logs', to='clients.businessclient')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='VoiceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='en', max_length=10)),
                ('voice_id', models.CharField(blank=True, max_length=160)),
                ('speed', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('stability', models.DecimalField(decimal_places=2, default=0.5, max_digits=4)),
                ('similarity_boost', models.DecimalField(decimal_places=2, default=0.75, max_digits=4)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voice_settings', to='clients.businessclient')),
            ],
        ),
    ]
