# Generated by Django 5.1.4 on 2026-05-31 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_core', '0001_initial'),
        ('appointments', '0006_alter_appointment_status'),
        ('clients', '0008_businessclient_logo_and_contacts'),
        ('staff_services', '0002_staffmember_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('next_in_line', 'Next in line'), ('urgent', 'Urgent — direct conversation requested'), ('notification', 'Notification')], default='notification', max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('speak_text', models.TextField(blank=True)),
                ('speak_lang', models.CharField(default='en', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('channels', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alarm_events', to='appointments.appointment')),
                ('business_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarm_events', to='clients.businessclient')),
                ('target_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alarm_events', to='staff_services.staffmember')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['business_client', 'dismissed_at', '-created_at'], name='ai_core_ala_busines_1ed441_idx'), models.Index(fields=['appointment', 'kind'], name='ai_core_ala_appoint_e40c41_idx')],
            },
        ),
    ]
