# Generated by Django 5.1.4 on 2026-04-26 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('public_name', models.CharField(blank=True, max_length=160)),
                ('package', models.CharField(choices=[('basic', 'Basic'), ('pro', 'Pro'), ('business', 'Business'), ('god_mode', 'GOD MODE')], default='basic', max_length=30)),
                ('language', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('pt', 'Portuguese'), ('ru', 'Russian'), ('sr', 'Serbian'), ('fr', 'French'), ('it', 'Italian')], default='en', max_length=10)),
                ('interface_language', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('pt', 'Portuguese'), ('ru', 'Russian'), ('sr', 'Serbian'), ('fr', 'French'), ('it', 'Italian')], default='en', max_length=10)),
                ('voice_language', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('pt', 'Portuguese'), ('ru', 'Russian'), ('sr', 'Serbian'), ('fr', 'French'), ('it', 'Italian')], default='en', max_length=10)),
                ('timezone', models.CharField(default='Europe/Belgrade', max_length=80)),
                ('kaleya_enabled', models.BooleanField(default=True)),
                ('work_start', models.TimeField(default='09:00')),
                ('work_end', models.TimeField(default='16:00')),
                ('slot_interval_minutes', models.PositiveIntegerField(default=30)),
                ('time_format', models.CharField(choices=[('24h', '24h'), ('12h', 'AM/PM')], default='24h', max_length=10)),
                ('week_start', models.IntegerField(choices=[(0, 'Monday'), (6, 'Sunday')], default=0)),
                ('allow_phone_calls', models.BooleanField(default=True)),
                ('allow_sms', models.BooleanField(default=True)),
                ('allow_whatsapp', models.BooleanField(default=True)),
                ('allow_viber', models.BooleanField(default=True)),
                ('allow_telegram', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_clients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ClientApiSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_provider', models.CharField(default='openai', max_length=80)),
                ('ai_model', models.CharField(default='gpt-4o-mini', max_length=120)),
                ('ai_api_key', models.CharField(blank=True, max_length=500)),
                ('voice_provider', models.CharField(default='elevenlabs', max_length=80)),
                ('voice_model', models.CharField(blank=True, max_length=120)),
                ('voice_api_key', models.CharField(blank=True, max_length=500)),
                ('voice_id', models.CharField(blank=True, max_length=160)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='api_settings', to='clients.businessclient')),
            ],
        ),
    ]
