# Generated by Django 5.1.4 on 2026-04-28 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_businessclient_date_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessclient',
            name='package',
            field=models.CharField(choices=[('basic', 'Basic'), ('pro', 'Pro'), ('business', 'Business'), ('business_plus', 'Business+'), ('business_pro_plus', 'BusinessPro+'), ('god_mode', 'GOD MODE')], default='basic', max_length=30),
        ),
    ]
