# Generated by Django 5.1.4 on 2026-04-28 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_businessclient_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessclient',
            name='interface_language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('pt', 'Portuguese'), ('ru', 'Russian'), ('sr', 'Serbian'), ('fr', 'French'), ('it', 'Italian'), ('de', 'German')], default='en', max_length=10),
        ),
        migrations.AlterField(
            model_name='businessclient',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('pt', 'Portuguese'), ('ru', 'Russian'), ('sr', 'Serbian'), ('fr', 'French'), ('it', 'Italian'), ('de', 'German')], default='en', max_length=10),
        ),
        migrations.AlterField(
            model_name='businessclient',
            name='voice_language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('pt', 'Portuguese'), ('ru', 'Russian'), ('sr', 'Serbian'), ('fr', 'French'), ('it', 'Italian'), ('de', 'German')], default='en', max_length=10),
        ),
    ]
