# Generated by Django 5.1.4 on 2026-05-05 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_businessclient_is_demo'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessKnowledgeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('faq', 'FAQ'), ('policy', 'Policy'), ('pricing', 'Pricing'), ('location', 'Location'), ('preparation', 'Preparation'), ('custom', 'Custom')], default='faq', max_length=40)),
                ('language', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('pt', 'Portuguese'), ('ru', 'Russian'), ('sr', 'Serbian'), ('fr', 'French'), ('it', 'Italian'), ('de', 'German')], default='en', max_length=10)),
                ('title', models.CharField(max_length=180)),
                ('answer', models.TextField()),
                ('keywords', models.CharField(blank=True, max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_entries', to='clients.businessclient')),
            ],
            options={
                'ordering': ('category', 'title'),
                'indexes': [models.Index(fields=['business_client', 'language', 'category', 'is_active'], name='clients_bus_busines_f9f2e2_idx')],
            },
        ),
    ]
