# Generated by Django 5.1.4 on 2026-06-14 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_businessclient_logo_and_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessclient',
            name='business_type',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='businessclient',
            name='country',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AddField(
            model_name='businessclient',
            name='website',
            field=models.URLField(blank=True, default=''),
        ),
    ]
