# Generated by Django 5.1.4 on 2026-05-30 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0008_businessclient_logo_and_contacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelnyxPhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='E.164 format, e.g. +12364773103', max_length=30, unique=True)),
                ('country_code', models.CharField(choices=[('US', 'United States'), ('CA', 'Canada'), ('GB', 'United Kingdom'), ('RS', 'Serbia'), ('HR', 'Croatia'), ('BA', 'Bosnia'), ('ME', 'Montenegro'), ('OTHER', 'Other')], default='US', max_length=10)),
                ('voice_enabled', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('telnyx_number_id', models.CharField(blank=True, help_text='Telnyx internal number ID', max_length=80)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('business_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telnyx_numbers', to='clients.businessclient')),
            ],
            options={
                'ordering': ('-purchased_at',),
                'indexes': [models.Index(fields=['phone_number'], name='telnyx_teln_phone_n_1aba5c_idx')],
            },
        ),
    ]
